version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: compliancelab_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: compliancelab_db
      POSTGRES_USER: compliancelab
      POSTGRES_PASSWORD: cl_password_2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compliancelab -d compliancelab_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: compliancelab_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    name: compliancelab_postgres_data
